### PR TITLE
Prevent collisions in env vars when using multiple SCMs of the same kind

### PR DESCRIPTION
**Pull request by JakeStoeffler**
The PR fixes an issue where if you're using multiple SCMs of the same kind (3 Git repos, for instance), you can only access the env vars of the last SCM declared in the job configuration.  This is because the env vars were being overwritten during each iteration in `buildEnvVars()`.

With this PR, you can now access each SCM's env vars individually.  For example, you can access the commit hash of 3 different Git SCMs using `GIT_COMMIT`, `GIT_COMMIT_1`, AND `GIT_COMMIT_2`.

To be honest, this is my first time contributing to a Jenkins plugin and I don't mind if this doesn't get merged into master -- I can continue using my own fork.  I just figured that creating a PR would get some visibility and this code might be helpful to someone else.

### CODE REVIEW

**Comment by jskjons** [comment]
this would be super useful for our usage of this plugin as well

**Comment by Brantone** [comment]
:+1:

**Comment by fergie** [comment]
:+1: Keen to see this merged for our usage too

**Comment by zerthimon** [comment]
Is this going to get merged any time soon ?

**Comment by liu2qian** [comment]
Also encountered the same problem, suggested merging this PR

**Comment by rodrigc** [comment]
Merged

**Comment by Sauraus** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-34249

**Pull request closed without merging**
