### PR TITLE
Retain backward compatibility for ENV vars

### PR DESCRIPTION
**Pull request by Sauraus**

### CODE REVIEW

**Comment by willneumob** [comment]
This still only shows `GIT_COMMIT_1` and no `GIT_COMMIT_2` - `GIT_COMMIT_4` for a 4-repository project.

**Comment by Sauraus** [comment]
That would suggest that the multi SCM plugin actually doesn't gets that info, if you look at the code it merely iterates over the entries it gets from the SCM plugin used, if it doesn't exist then it can't create _1/2/3/4 etc. variants of it.

**Comment by willneumob** [comment]
This must be an unrelated bug, then. It has the URLs for the other Git repositories, and any of them could have triggered the build. I don't see any possible way to get the commit hashes for all repositories during the build, without calling `git ls-remote` (which could cause a race condition).

**Comment by willneumob** [comment]
One problem I've seen with this patch is that the existing indexed variables like `GIT_URL_1..4` become `GIT_URL_1_1` `GIT_URL_2_1` .. `GIT_URL_4_1`, which doesn't seem desirable. Maybe make it ignore variables that already end in `_[0-9]+`.

**Comment by Sauraus** [comment]
What did the code do before with GIT? Because with perforce it does _1/2/3/4... etc. there is no PERFORCE_1_1 etc. Seems weird that it would do this for GIT but not for PERFORCE.

**Comment by Sauraus** [comment]
@rodrigc the current plugin breaks backward compatibility.

**Comment by Sauraus** [comment]
@kmbell @jglick @elksson anyone else that can take a look at this pull request, because the current SCM multi plugin had broken backwards compatibility.

**Comment by Sauraus** [comment]
@oleg-nenashev can you take a look at this please?

**Comment by jacob-keller** [comment]
It looks reasonable to me, and better than what is released right now. All variables should be indexed, even if they have some (probably unrelated) index already, as there is no way to know for sure that the index is for the SCM number.

**Pull request closed without merging**
