### PR TITLE
JENKINS-56109 Convert table to div

### PR DESCRIPTION
**Pull request by timja**
Applying matching changes from core as this plugin forked hetero-list
https://github.com/jenkinsci/jenkins/pull/3895

To be merged after above has been released, the minimum jenkins version should also be increased to match the version the above is released in,

Planning to merge the core PR soon after the next LTS is picked, after 6th May

### CODE REVIEW

**Comment by fqueiruga** [comment]
Shouldn't this include a bump in the minimum jenkins  version? I suppose you're waiting for the weekly with the form changes to be released right?

**Comment by timja** [comment]
> Shouldn't this include a bump in the minimum jenkins version? I suppose you're waiting for the weekly with the form changes to be released right?

yes, now that I've figured out the wrapper approach as well, that would work here so it wouldn't be needed, I didn't invest too much time on this plugin as it already seems partially broken (i.e. doesn't seem to work in pipeline)

**Comment by timja** [comment]
> Shouldn't this include a bump in the minimum jenkins version? I suppose you're waiting for the weekly with the form changes to be released right?

Made it compatible, untested the last change though

**Comment by timja** [comment]
This plugin is deprecated and broken before this change anyway

**Comment by jimklimov** [comment]
Just FYI: we use it intensively in some remaining legacy freestyle jobs, and it is not broken there :) 

For comparison, a few of our pipeline jobs that combine code from several SCMs do use the `checkout` step with lots of parameters, often also lock-pick the credentials to use based in git URLs (ssh key vs http login) and add SSH agent wrapping closure.

**Comment by timja** [comment]
The plugin has no maintainer, and is marked as deprecated in the update center.

If you want to continue with it might be easiest to use a custom build? Or take over maintainership

**Comment by oleg-nenashev** [comment]
+1 for taking ownership. We can get the fix merged, address other issues and republish the plugin if there are active contributors.

**Comment by kwart** [comment]
Could this one be reopened and merged?

**Comment by jimklimov** [comment]
I hope so, getting to maintain the plugin so it stays afloat some more.
I'll check vs. custom build that runs on my farm that needed it, if this
was all the needed change.

**Comment by kwart** [comment]
We use `jenkins/jenkins:lts` Docker image in Hazelcast. After updating to 2.277.z the Multiple SCM stopped working. Using fix from this PR worked for us.

We have more than 250 jobs using the MultiSCM so we would be really happy to have an "official" plugin release with the fix.

**Pull request closed without merging**
